workflows:
  ios-build:
    name: iOS Build (Development)
    max_build_duration: 120
    instance_type: mac_mini_m2
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
      flutter: stable
      xcode: latest
      cocoapods: default
      ios_signing:  #
        distribution_type: development  
        bundle_identifier: com.fabianvalero.todor5  
        team_id: AUTO  
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Clean iOS Pods
        script: |
          cd ios
          rm -rf Pods .symlinks Flutter/Flutter.podspec
          pod install --repo-update
          cd ..
      - name: Build iOS App
        script: |
          flutter build ios --debug --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa  
    publishing:
      email:
        recipients:
          - djfabianvalero@gmail.com