workflows:
  ios:
    name: Build iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: 16.1  
      node: latest  

    scripts:
      - name: Set up Flutter environment
        script: |
          flutter channel stable
          flutter upgrade
          flutter doctor

      - name: Install dependencies
        script: |
          # Instalar dependencias de Flutter
          flutter pub get
          
          # Verificar si el directorio 'ios' existe y contiene el archivo Podfile
          if [ -d "ios" ]; then
            echo "Directorio ios encontrado"
          else
            echo "Error: El directorio ios no existe"
            exit 1
          fi

          # Verificar si el archivo Podfile está presente
          if [ ! -f "ios/Podfile" ]; then
            echo "Error: El archivo Podfile no se encuentra en ios/"
            exit 1
          fi

          # Instalar CocoaPods
          gem install cocoapods
          pod repo update

          # Hacer una instalación limpia de CocoaPods
          cd ios
          pod install --clean-install --repo-update --verbose

      - name: Build iOS release
        script: |
          # Compilar para iOS sin códigosignature
          flutter build ios --release --no-codesign --verbose

      - name: Upload build artifact
        script: |
          # Subir el archivo generado a algún lugar, si es necesario
          mkdir -p $CM_BUILD_DIR/artifacts
          cp -r build/ios/iphoneos/*.ipa $CM_BUILD_DIR/artifacts/
