workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Establecer iOS Deployment Target en 13.0
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile
      - name: Instalar dependencias
        script: |
          cd ios
          pod install
