workflows:
  ios:
    name: Build iOS
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: default  
      node: latest  
      ruby: latest  

    scripts:
      - name: Set up Flutter environment
        script: |
          flutter channel stable
          flutter upgrade
          flutter doctor

      - name: Install dependencies
        script: |
          # Instalar dependencias de Flutter
          flutter pub get
          
          # Instalar CocoaPods
          gem install cocoapods
          pod install --project-directory=ios

      - name: Build iOS release
        script: |
          # Compilar para iOS
          flutter build ios --release --no-codesign
          
      - name: Upload build artifact
        script: |
          # Subir el archivo generado a algún lugar, si es necesario
          mkdir -p $CM_BUILD_DIR/artifacts
          cp -r build/ios/iphoneos/*.ipa $CM_BUILD_DIR/artifacts/
