workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Asegurar que la carpeta iOS existe
        script: |
          if [ ! -d "ios" ]; then
            flutter create .
          fi
      - name: Establecer iOS Deployment Target en 13.0
        script: |
          if [ ! -f "ios/Podfile" ]; then
            echo "platform :ios, \"13.0\"" > ios/Podfile
          fi
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile
      - name: Ejecutar flutter pub get
        script: |
          flutter pub get
      - name: Instalar dependencias de CocoaPods
        script: |
          cd ios
          pod install --repo-update
