workflows:
  ios-app:
    name: iOS Build Workflow
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Configurar iOS Deployment Target a 13.0
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile

      - name: Instalar dependencias de CocoaPods
        script: |
          cd ios
          pod repo update
          pod install --verbose

      - name: Compilar la aplicación Flutter para iOS
        script: |
          flutter clean
          flutter pub get
          flutter build ios --no-codesign

    artifacts:
      - build/ios/iphoneos/*.ipa
      - build/ios/iphoneos/*.app

    publishing:
      email:
        recipients:
          - "disdesoft@gmail.com"