workflows:
  ios-build:
    name: iOS Build
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      vars:
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        APP_STORE_CONNECT_KEY: ENCODED_APP_STORE_KEY
      flutter: stable
      xcode: latest
    scripts:
      - name: Clean Flutter
        script: |
          flutter clean
          flutter pub get
      - name: Clean iOS Pods
        script: |
          rm -rf ios/Pods ios/.symlinks ios/Flutter/Flutter.podspec
          cd ios
          pod install --repo-update
          cd ..
      - name: Build iOS App
        script: |
          flutter build ios --debug --no-codesign
