workflows:
  ios-build:
    name: iOS Build
    environment:
      flutter: stable
    scripts:
      - name: Limpiar y crear el proyecto iOS
        script: |
          rm -rf ios
          flutter create .
      - name: Configurar el deployment target a iOS 13
        script: |
          sed -i '' 's/platform :ios, .*/platform :ios, "13.0"/' ios/Podfile
      - name: Ejecutar flutter pub get
        script: |
          flutter pub get
      - name: Instalar dependencias de CocoaPods
        script: |
          cd ios
          pod install --repo-update
